-- Create Channels table for Live TV feature
CREATE TABLE IF NOT EXISTS "Channels" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  group_title TEXT DEFAULT 'Indonesia Channels',
  logo TEXT,
  stream_url TEXT NOT NULL,
  stream_type TEXT DEFAULT 'hls',
  http_headers TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE "Channels" ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Public read Channels" ON "Channels";
DROP POLICY IF EXISTS "Admin write Channels" ON "Channels";

-- Public read access
CREATE POLICY "Public read Channels" ON "Channels" FOR SELECT USING (true);

-- Admin write access (authenticated session required)
CREATE POLICY "Admin write Channels" ON "Channels"
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
